#!/usr/bin/env bash
#
# Move AI Smart Store's database off the hosting provider's managed project and
# onto one you own.
#
# Run this from a machine that can reach both databases on port 5432. That is
# almost certainly your own laptop -- CI runners and agent sandboxes generally
# cannot open raw Postgres connections, which is the whole reason this is a
# script you run rather than something already done for you.
#
#   ./migrate.sh
#
# Reads two connection strings from the environment. Both are on the
# "Connect" button of the respective Supabase project dashboard; use the
# *direct* connection string, not the pooler -- pg_dump needs session mode.
#
#   SOURCE_DB_URL   the project being left
#   TARGET_DB_URL   the project being moved to
#
# Optional:
#   KEEP_INACTIVE=1   copy all ~175,000 products instead of only the active
#                     ones. See "About the catalogue" below before setting it.
#   DATA_ONLY=1       skip the extension and schema steps and reload rows only.
#                     Use this to re-sync data onto a target whose schema is
#                     already in place -- e.g. a second pass just before
#                     cutover, to pick up orders placed since the first run.
#
# Safe to re-run. Every table is truncated before it is reloaded, so a failed
# run leaves nothing half-merged, and a second run converges.
#
# What this script does NOT do, because it cannot:
#   * copy Storage objects (the product-images bucket). Those are files behind
#     an HTTP API, not rows. See RUNBOOK.md step 6.
#   * copy edge function secrets. They are write-only by design. RUNBOOK step 4.
#   * repoint DNS. RUNBOOK step 8.

set -euo pipefail

: "${SOURCE_DB_URL:?set SOURCE_DB_URL to the source project's direct connection string}"
: "${TARGET_DB_URL:?set TARGET_DB_URL to the target project's direct connection string}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# Tables in foreign-key order: a table never appears before something it
# references. Derived from the live schema, not hand-maintained.
TABLES=(
  addresses ai_conversations ai_pulse_feeds ai_pulse_items ai_usage_log
  automation_events brands categories compliance_access_log compliance_documents
  data_retention_policy email_send_log email_send_state email_unsubscribe_tokens
  engine_registry engine_room_assessments exchange_rates image_blocklist
  newsletter_campaigns newsletter_subscribers notification_preferences
  notifications orders product_facets_cache profile_admin_notes profiles
  quote_requests rate_limit_buckets returns security_events sms_send_log
  spend_caps spend_ledger store_settings suppressed_emails sync_logs
  threat_blocks threat_quarantine threat_signatures user_roles
  ai_pulse_feed_requests newsletter_story_sends order_audit_log payment_events
  products support_tickets home_showcase order_items product_costs
  ticket_messages wishlists
)

say "Checking both databases are reachable"
psql "$SOURCE_DB_URL" -Atqc 'select 1' >/dev/null
psql "$TARGET_DB_URL" -Atqc 'select 1' >/dev/null
echo "    both OK"

if [[ "${DATA_ONLY:-0}" == "1" ]]; then
  say "DATA_ONLY=1 -- skipping extensions and schema, reloading rows only"
fi

# --------------------------------------------------------------------- 1/5
if [[ "${DATA_ONLY:-0}" != "1" ]]; then
say "1/5  Extensions"
# Schemas match the source project exactly, verified against its pg_extension.
# This is not cosmetic: schema.sql declares two indexes as
# `USING gin (... extensions.gin_trgm_ops)`, so pg_trgm landing anywhere other
# than `extensions` fails those two index creations -- and it fails them
# quietly in the middle of a 4,800-line script, leaving product search without
# its trigram indexes and every catalogue query on a sequential scan.
psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto    WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm     WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net      WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgmq;
CREATE EXTENSION IF NOT EXISTS supabase_vault;
CREATE EXTENSION IF NOT EXISTS pg_cron;
SQL

# Fail loudly here rather than 4,000 lines into the schema load.
psql "$TARGET_DB_URL" -Atqc "select 1 from pg_opclass o join pg_namespace n on n.oid=o.opcnamespace where o.opcname='gin_trgm_ops' and n.nspname='extensions'" | grep -q 1 \
  || { echo "FATAL: extensions.gin_trgm_ops not found -- pg_trgm is installed in the wrong schema."; exit 1; }

# --------------------------------------------------------------------- 2/5
say "2/5  Schema"
# schema.sql is generated by rebuilding this repo's migrations into an empty
# PostgreSQL 16 cluster and dumping the result. It is verified to reproduce the
# live database's 51 tables, 90 RLS policies and both views exactly.
psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -q -f "$HERE/schema.sql"
echo "    $(psql "$TARGET_DB_URL" -Atqc "select count(*) from information_schema.tables where table_schema='public' and table_type='BASE TABLE'") tables created"
fi  # DATA_ONLY

# --------------------------------------------------------------------- 3/5
say "3/5  Accounts (auth schema)"
# Password hashes and OAuth identities live in auth.*, and cannot be
# reconstructed from the public schema. Without this step every existing
# customer's login silently stops working -- they are not "missing", they are
# unable to sign in, which is worse because nothing looks broken.
#
# --data-only against the tables that hold identity. Supabase manages the auth
# schema's shape, so only rows move.
pg_dump "$SOURCE_DB_URL" --data-only --no-owner --no-privileges \
  --table='auth.users' --table='auth.identities' \
  > "$WORK/auth.sql"
psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -q <<'SQL'
TRUNCATE auth.identities, auth.users CASCADE;
SQL
psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -q -f "$WORK/auth.sql"
echo "    $(psql "$TARGET_DB_URL" -Atqc 'select count(*) from auth.users') accounts"

# --------------------------------------------------------------------- 4/5
say "4/5  Data"

# About the catalogue.
#
# The source database is ~456MB, of which 406MB is the products table and 23MB
# is product_costs. Roughly 172,000 of those ~175,000 product rows are
# is_active = false: distributor SKUs that failed the price-sanity, image or
# category gates and are invisible on the storefront. They are not customer
# data and they are re-derivable -- the Axiz sync rebuilds them.
#
# Copying only the active catalogue takes the database from ~456MB to a few MB,
# which is the difference between fitting a free tier and not. Set
# KEEP_INACTIVE=1 to copy everything anyway.
if [[ "${KEEP_INACTIVE:-0}" == "1" ]]; then
  PRODUCT_WHERE=""
  echo "    KEEP_INACTIVE=1 -- copying the full catalogue"
else
  PRODUCT_WHERE="WHERE is_active"
  echo "    copying active products only (set KEEP_INACTIVE=1 to copy all)"
fi

# Extract every table to its own TSV first, so that a failure is attributable
# to one table instead of a broken pipe halfway through the run.
#
# Columns are named explicitly rather than using SELECT * / COPY table, for two
# reasons that both bite silently:
#
#   1. GENERATED columns. products.search_vector is `GENERATED ALWAYS AS`.
#      COPY TO emits it; COPY FROM refuses to accept a value for it. An
#      unqualified copy of the products table therefore fails with "extra data
#      after last expected column" -- and since that is one table's error in
#      the middle of fifty, it is easy to end up with a catalogue-shaped hole.
#
#   2. Column ORDER. COPY without a column list is positional. The source
#      gained several columns via ALTER TABLE over its life, so its physical
#      column order is a history, not a design. Naming the columns means the
#      two databases do not have to agree on that history.
#
# The list comes from the TARGET, so anything the target does not have is
# simply not requested.
say "     extracting from source"
for t in "${TABLES[@]}"; do
  COLS=$(psql "$TARGET_DB_URL" -Atqc "
    SELECT string_agg(quote_ident(attname), ', ' ORDER BY attnum)
      FROM pg_attribute
     WHERE attrelid = 'public.$t'::regclass
       AND attnum > 0 AND NOT attisdropped AND attgenerated = ''")

  case "$t" in
    products)
      SRC="COPY (SELECT $COLS FROM public.products $PRODUCT_WHERE) TO STDOUT" ;;
    product_costs)
      # Costs for products that did not come across would violate the foreign
      # key, and are meaningless on their own.
      # Sub-select rather than a join: product_costs and products share column
      # names (updated_at), so an unaliased join is ambiguous, and aliasing a
      # generated column list correctly is more fragile than avoiding it.
      if [[ -n "$PRODUCT_WHERE" ]]; then
        SRC="COPY (SELECT $COLS FROM public.product_costs WHERE product_id IN (SELECT id FROM public.products WHERE is_active)) TO STDOUT"
      else
        SRC="COPY (SELECT $COLS FROM public.product_costs) TO STDOUT"
      fi ;;
    *)
      SRC="COPY (SELECT $COLS FROM public.$t) TO STDOUT" ;;
  esac

  psql "$SOURCE_DB_URL" -v ON_ERROR_STOP=1 -Atq -c "$SRC" > "$WORK/$t.tsv"
  echo "$COLS" > "$WORK/$t.cols"
done
echo "    $(du -sh "$WORK" | cut -f1) extracted"

# Load everything in ONE psql session, because the two things that make this
# correct are session-scoped.
#
#   session_replication_role = replica  disables user triggers and foreign-key
#   checks for the duration. This is what pg_restore does, and it is not an
#   optimisation -- `orders` has an AFTER INSERT trigger that writes the order
#   audit trail, so copying orders with triggers live invents a second
#   "order_created" audit row for every order that already had one. The audit
#   log is the record of who changed what on an order; silently doubling it
#   during a migration is exactly the kind of thing nobody notices until it is
#   evidence in a dispute.
#
#   \copy runs client-side, so it can read these local files without the
#   database server needing filesystem access.
say "     loading into target"
{
  echo "SET session_replication_role = 'replica';"
  echo "BEGIN;"
  # Truncate in reverse FK order, then load forwards.
  for (( i=${#TABLES[@]}-1 ; i>=0 ; i-- )); do
    echo "TRUNCATE public.${TABLES[i]} CASCADE;"
  done
  for t in "${TABLES[@]}"; do
    # Same explicit column list the extract used, so the load is by name and
    # not by position. Empty files still count: an empty table on the source
    # must not silently become a table that was skipped.
    echo "\\copy public.$t ($(cat "$WORK/$t.cols")) FROM '$WORK/$t.tsv'"
  done
  echo "COMMIT;"
  echo "SET session_replication_role = 'origin';"
} > "$WORK/load.sql"

psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -q -f "$WORK/load.sql"
echo "    loaded"

# --------------------------------------------------------------------- 5/5
say "5/5  Point the database at its new home"
NEW_REF=$(psql "$TARGET_DB_URL" -Atqc "select current_setting('app.settings.project_ref', true)" || true)
if [[ -z "$NEW_REF" ]]; then
  echo "    Could not detect the project ref automatically."
  echo "    Set it by hand -- this is the one row that repoints every scheduled job:"
  echo
  echo "      UPDATE store_settings SET value = 'https://<new-ref>.supabase.co/functions/v1'"
  echo "       WHERE key = 'functions_base_url';"
else
  psql "$TARGET_DB_URL" -v ON_ERROR_STOP=1 -q -c \
    "UPDATE store_settings SET value = 'https://$NEW_REF.supabase.co/functions/v1' WHERE key = 'functions_base_url';"
  echo "    functions_base_url -> https://$NEW_REF.supabase.co/functions/v1"
fi

say "Row counts, source vs target"
printf '     %-28s %10s %10s\n' TABLE SOURCE TARGET
for t in "${TABLES[@]}"; do
  s=$(psql "$SOURCE_DB_URL" -Atqc "select count(*) from public.$t")
  d=$(psql "$TARGET_DB_URL" -Atqc "select count(*) from public.$t")
  flag=""
  [[ "$s" != "$d" ]] && flag="  <-- differs"
  [[ "$t" == "products" || "$t" == "product_costs" ]] && [[ -n "$PRODUCT_WHERE" ]] && flag="  (inactive intentionally dropped)"
  printf '     %-28s %10s %10s%s\n' "$t" "$s" "$d" "$flag"
done

say "Database moved. Remaining steps are in RUNBOOK.md, from step 4."
